using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wfrp4.Infrastructure.Data;

#nullable disable

namespace Wfrp4.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(Wfrp4DbContext))]
    [Migration("20261004120000_AddParties")]
    public partial class AddParties : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE "Parties" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Nom" character varying(120) NOT NULL,
                    "Description" character varying(2000) NULL,
                    "Type" character varying(20) NOT NULL,
                    "Statut" character varying(20) NOT NULL,
                    "MjKeycloakId" character varying(100) NOT NULL,
                    "MjNom" character varying(100) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Parties" PRIMARY KEY ("Id")
                );

                CREATE INDEX "IX_Parties_MjKeycloakId" ON "Parties" ("MjKeycloakId");

                CREATE TABLE "PartieMembres" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "PartieId" integer NOT NULL,
                    "JoueurKeycloakId" character varying(100) NOT NULL,
                    "JoueurNom" character varying(100) NOT NULL,
                    "PersonnageId" integer NULL,
                    "AjouteLe" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_PartieMembres" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PartieMembres_Parties_PartieId" FOREIGN KEY ("PartieId")
                        REFERENCES "Parties" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_PartieMembres_Personnages_PersonnageId" FOREIGN KEY ("PersonnageId")
                        REFERENCES "Personnages" ("Id") ON DELETE SET NULL
                );

                CREATE UNIQUE INDEX "IX_PartieMembres_PartieId_JoueurKeycloakId" ON "PartieMembres" ("PartieId", "JoueurKeycloakId");
                CREATE INDEX "IX_PartieMembres_JoueurKeycloakId" ON "PartieMembres" ("JoueurKeycloakId");
                CREATE INDEX "IX_PartieMembres_PersonnageId" ON "PartieMembres" ("PersonnageId");

                ALTER TABLE "PersonnagePartages" ADD "PartieId" integer NULL;
                ALTER TABLE "PersonnagePartages" ADD CONSTRAINT "FK_PersonnagePartages_Parties_PartieId"
                    FOREIGN KEY ("PartieId") REFERENCES "Parties" ("Id") ON DELETE SET NULL;
                CREATE INDEX "IX_PersonnagePartages_PartieId" ON "PersonnagePartages" ("PartieId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DROP INDEX IF EXISTS "IX_PersonnagePartages_PartieId";
                ALTER TABLE "PersonnagePartages" DROP CONSTRAINT IF EXISTS "FK_PersonnagePartages_Parties_PartieId";
                ALTER TABLE "PersonnagePartages" DROP COLUMN IF EXISTS "PartieId";
                DROP TABLE IF EXISTS "PartieMembres";
                DROP TABLE IF EXISTS "Parties";
                """);
        }
    }
}
