using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Wfrp4.Infrastructure.Data;

#nullable disable

namespace Wfrp4.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(Wfrp4DbContext))]
    [Migration("20260915120000_AddAventuresSauvegardees")]
    public partial class AddAventuresSauvegardees : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE "AventuresSauvegardees" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "KeycloakId" character varying(100) NOT NULL,
                    "Type" character varying(20) NOT NULL,
                    "Titre" character varying(300) NOT NULL,
                    "DataJson" jsonb NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_AventuresSauvegardees" PRIMARY KEY ("Id")
                );

                CREATE INDEX "IX_AventuresSauvegardees_KeycloakId" ON "AventuresSauvegardees" ("KeycloakId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "AventuresSauvegardees";""");
        }
    }
}
