// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wfrp4.Infrastructure.Data;

#nullable disable

namespace Wfrp4.Infrastructure.Data.Migrations
{
    [DbContext(typeof(Wfrp4DbContext))]
    [Migration("20260830161405_AddCreationFreeCounters")]
    partial class AddCreationFreeCounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.ArmeReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Defauts")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("DeuxMains")
                        .HasColumnType("boolean");

                    b.Property<string>("Disponibilite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dommage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Encombrement")
                        .HasColumnType("integer");

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Longueur")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Portee")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prix")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Qualites")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TypeArme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ArmesReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Carriere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EspecesAutorisees")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Carrieres");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caracteristique")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("EstAvancee")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstGroupee")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.CreatureReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ag")
                        .HasColumnType("integer");

                    b.Property<int>("B")
                        .HasColumnType("integer");

                    b.Property<int>("CC")
                        .HasColumnType("integer");

                    b.Property<int>("CT")
                        .HasColumnType("integer");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Dex")
                        .HasColumnType("integer");

                    b.Property<int>("E")
                        .HasColumnType("integer");

                    b.Property<int>("F")
                        .HasColumnType("integer");

                    b.Property<int>("FM")
                        .HasColumnType("integer");

                    b.Property<int>("I")
                        .HasColumnType("integer");

                    b.Property<int>("Int")
                        .HasColumnType("integer");

                    b.Property<int>("M")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<int>("Soc")
                        .HasColumnType("integer");

                    b.Property<string>("Traits")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TraitsOptionnels")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CreaturesReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Espece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaracInitiales")
                        .HasColumnType("jsonb");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MouvementBase")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraitsPhysiques")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Especes");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.HistoriqueXP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuteurKeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cible")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Montant")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonnageId");

                    b.ToTable("HistoriqueXPs");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.NiveauCarriere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvancesCarac")
                        .HasColumnType("jsonb");

                    b.Property<int>("CarriereId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetenceRevenu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Dotations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("StatutNumerique")
                        .HasColumnType("integer");

                    b.Property<string>("TalentsRevenu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CarriereId");

                    b.ToTable("NiveauCarrieres");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AmbitionCourtTerme")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AmbitionLongTerme")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("AvancesCompetenceGratuitesRestantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BlessuresMax")
                        .HasColumnType("integer");

                    b.Property<int?>("CarriereCouranteId")
                        .HasColumnType("integer");

                    b.Property<string>("CorruptionMutations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CouleurCheveux")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CouleurYeux")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CouronnesOr")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Destin")
                        .HasColumnType("integer");

                    b.Property<int>("EspeceId")
                        .HasColumnType("integer");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<int>("Fortune")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Masculin");

                    b.Property<string>("GroupeMembres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GroupeNom")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Motivation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Mouvement")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PistolesArgent")
                        .HasColumnType("integer");

                    b.Property<string>("Psychologie")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Resilience")
                        .HasColumnType("integer");

                    b.Property<int>("Resolution")
                        .HasColumnType("integer");

                    b.Property<int>("SousCuivre")
                        .HasColumnType("integer");

                    b.Property<string>("StatutSocial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("TailleCm")
                        .HasColumnType("integer");

                    b.Property<int>("TalentsGratuitsRestants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("TitreBaseReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TitreQualificatifReferenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpDepense")
                        .HasColumnType("integer");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CarriereCouranteId");

                    b.HasIndex("EspeceId");

                    b.HasIndex("KeycloakId");

                    b.HasIndex("TitreBaseReferenceId");

                    b.HasIndex("TitreQualificatifReferenceId");

                    b.ToTable("Personnages");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCaracteristique", b =>
                {
                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Avances")
                        .HasColumnType("integer");

                    b.Property<int>("ValeurInitiale")
                        .HasColumnType("integer");

                    b.HasKey("PersonnageId", "Code");

                    b.ToTable("PersonnageCaracteristiques");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCarriere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstCourante")
                        .HasColumnType("boolean");

                    b.Property<int>("NiveauCarriereId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NiveauCarriereId");

                    b.HasIndex("PersonnageId");

                    b.ToTable("PersonnageCarrieres");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCompetence", b =>
                {
                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("integer");

                    b.Property<int>("Avances")
                        .HasColumnType("integer");

                    b.HasKey("PersonnageId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("PersonnageCompetences");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageParchemin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("SortReferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortReferenceId");

                    b.HasIndex("PersonnageId", "SortReferenceId")
                        .IsUnique();

                    b.ToTable("PersonnageParchemins");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnagePartage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MjKeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonnageId", "MjKeycloakId")
                        .IsUnique();

                    b.ToTable("PersonnagePartages");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnagePossession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("PersonnageId");

                    b.ToTable("PersonnagePossessions");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageSort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("SortReferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortReferenceId");

                    b.HasIndex("PersonnageId", "SortReferenceId")
                        .IsUnique();

                    b.ToTable("PersonnageSorts");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageTalent", b =>
                {
                    b.Property<int>("PersonnageId")
                        .HasColumnType("integer");

                    b.Property<int>("TalentId")
                        .HasColumnType("integer");

                    b.Property<int>("Fois")
                        .HasColumnType("integer");

                    b.HasKey("PersonnageId", "TalentId");

                    b.HasIndex("TalentId");

                    b.ToTable("PersonnageTalents");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.SortReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cible")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("Cn")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Domaine")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Duree")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Portee")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Resume")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SortsReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Talent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Effet")
                        .HasColumnType("text");

                    b.Property<bool>("Empilable")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxFois")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.TitreBaseReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NiveauMaitrise")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TitresBaseReference", t =>
                        {
                            t.HasCheckConstraint("CK_TitresBaseReference_NiveauMaitrise", "\"NiveauMaitrise\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.TitreQualificatifReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NiveauMaitrise")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TitresQualificatifReference", t =>
                        {
                            t.HasCheckConstraint("CK_TitresQualificatifReference_NiveauMaitrise", "\"NiveauMaitrise\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Carriere", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Classe", "Classe")
                        .WithMany("Carrieres")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.HistoriqueXP", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", "Personnage")
                        .WithMany("HistoriqueXP")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.NiveauCarriere", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Carriere", "Carriere")
                        .WithMany("Niveaux")
                        .HasForeignKey("CarriereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carriere");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Personnage", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.NiveauCarriere", "CarriereCourante")
                        .WithMany()
                        .HasForeignKey("CarriereCouranteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wfrp4.Infrastructure.Entities.Espece", "Espece")
                        .WithMany()
                        .HasForeignKey("EspeceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.TitreBaseReference", "TitreBaseReference")
                        .WithMany()
                        .HasForeignKey("TitreBaseReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Wfrp4.Infrastructure.Entities.TitreQualificatifReference", "TitreQualificatifReference")
                        .WithMany()
                        .HasForeignKey("TitreQualificatifReferenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarriereCourante");

                    b.Navigation("Espece");

                    b.Navigation("TitreBaseReference");

                    b.Navigation("TitreQualificatifReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCaracteristique", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", null)
                        .WithMany("Caracteristiques")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCarriere", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.NiveauCarriere", "NiveauCarriere")
                        .WithMany()
                        .HasForeignKey("NiveauCarriereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", null)
                        .WithMany("Carrieres")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NiveauCarriere");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageCompetence", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Competence", "Competence")
                        .WithMany()
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", null)
                        .WithMany("Competences")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageParchemin", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", "Personnage")
                        .WithMany("Parchemins")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.SortReference", "SortReference")
                        .WithMany()
                        .HasForeignKey("SortReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personnage");

                    b.Navigation("SortReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnagePartage", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", "Personnage")
                        .WithMany("Partages")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnage");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnagePossession", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", null)
                        .WithMany("Possessions")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageSort", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", "Personnage")
                        .WithMany("Sorts")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.SortReference", "SortReference")
                        .WithMany()
                        .HasForeignKey("SortReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personnage");

                    b.Navigation("SortReference");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.PersonnageTalent", b =>
                {
                    b.HasOne("Wfrp4.Infrastructure.Entities.Personnage", null)
                        .WithMany("Talents")
                        .HasForeignKey("PersonnageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wfrp4.Infrastructure.Entities.Talent", "Talent")
                        .WithMany()
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Carriere", b =>
                {
                    b.Navigation("Niveaux");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Classe", b =>
                {
                    b.Navigation("Carrieres");
                });

            modelBuilder.Entity("Wfrp4.Infrastructure.Entities.Personnage", b =>
                {
                    b.Navigation("Caracteristiques");

                    b.Navigation("Carrieres");

                    b.Navigation("Competences");

                    b.Navigation("HistoriqueXP");

                    b.Navigation("Parchemins");

                    b.Navigation("Partages");

                    b.Navigation("Possessions");

                    b.Navigation("Sorts");

                    b.Navigation("Talents");
                });
#pragma warning restore 612, 618
        }
    }
}
